In [1]:
import pandas as pd
import numpy as np
import re

In [4]:
df = pd.read_csv(r"C:\\Users\\kunja\\Downloads\\Ecommerce_Vector_RAG\\data\\processed\\amazon_products_clean.csv")

df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,review_title,review_content,combined_text
0,B07JW9H4J1,wayona nylon braided usb to lightning fast cha...,computers accessories accessories peripherals ...,399.0,1099.0,64%,4.2,24269,high compatibility compatible with iphone 12 1...,satisfied charging is really fast value for mo...,looks durable charging is fine toono complains...,wayona nylon braided usb to lightning fast cha...
1,B098NS6PVG,ambrane unbreakable 60w 3a fast charging 1 5m ...,computers accessories accessories peripherals ...,199.0,349.0,43%,4.0,43994,compatible with all type c enabled devices be ...,a good braided cable for your type c device go...,i ordered this cable to connect my phone to an...,ambrane unbreakable 60w 3a fast charging 1 5m ...
2,B096MSW6CT,sounce fast phone charging cable data sync usb...,computers accessories accessories peripherals ...,199.0,1899.0,90%,3.9,7928,fast charger data sync with built in safety pr...,good speed for earlier versions good product w...,not quite durable and sturdy https m media ama...,sounce fast phone charging cable data sync usb...
3,B08HDJ86NZ,boat deuce usb 300 2 in 1 type c micro usb str...,computers accessories accessories peripherals ...,329.0,699.0,53%,4.2,94363,the boat deuce usb 300 2 in 1 cable is compati...,good product good one nice really nice product...,good product long wire charges good nice i bou...,boat deuce usb 300 2 in 1 type c micro usb str...
4,B08CF3B7N1,portronics konnect l 1 2m fast charging 3a 8 p...,computers accessories accessories peripherals ...,154.0,399.0,61%,4.2,16905,charge sync function this cable comes with cha...,as good as original decent good one for second...,bought this instead of original apple does the...,portronics konnect l 1 2m fast charging 3a 8 p...

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1397 entries, 0 to 1396
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1397 non-null   object
 1   product_name         1397 non-null   object
 2   category             1397 non-null   object
 3   discounted_price     1397 non-null   float64
 4   actual_price         1397 non-null   float64
 5   discount_percentage  1397 non-null   object
 6   rating               1397 non-null   float64
 7   rating_count         1397 non-null   int64
 8   about_product        1397 non-null   object
 9   review_title         1397 non-null   object
 10  review_content       1397 non-null   object
 11  combined_text        1397 non-null   object
dtypes: float64(3), int64(1), object(8)
memory usage: 131.1+ KB

In [6]:
df["discount_percentage"] = (
    df["discount_percentage"]
      .astype(str)
      .str.replace("%", "", regex=False)
)

df["discount_percentage"] = pd.to_numeric(
    df["discount_percentage"],
    errors="coerce"
)

In [7]:
df["discount_amount"] = (
    df["actual_price"]
    - df["discounted_price"]
)

In [8]:
df["description_length"] = (
    df["about_product"]
    .fillna("")
    .str.len()
)

In [9]:
df["review_length"] = (
    df["review_content"]
    .fillna("")
    .str.len()
)

In [10]:
df["product_name_length"] = (
    df["product_name"]
    .str.len()
)

In [11]:
df["category_depth"] = (
    df["category"]
      .astype(str)
      .str.count(r"\|")
      + 1
)

In [12]:
df["combined_text"] = (
    "Product Name: " + df["product_name"] +
    ". Category: " + df["category"] +
    ". Description: " + df["about_product"] +
    ". Review Title: " + df["review_title"] +
    ". Review: " + df["review_content"] +
    ". Rating: " + df["rating"].astype(str)
)

In [13]:
df["combined_text"] = (
    df["combined_text"]
      .str.replace(r"\s+", " ", regex=True)
      .str.strip()
)

In [14]:
df[[
    "product_name",
    "combined_text",
    "description_length",
    "review_length"
]].head()

,product_name,combined_text,description_length,review_length
0,wayona nylon braided usb to lightning fast cha...,Product Name: wayona nylon braided usb to ligh...,936,467
1,ambrane unbreakable 60w 3a fast charging 1 5m ...,Product Name: ambrane unbreakable 60w 3a fast ...,583,1169
2,sounce fast phone charging cable data sync usb...,Product Name: sounce fast phone charging cable...,1048,265
3,boat deuce usb 300 2 in 1 type c micro usb str...,Product Name: boat deuce usb 300 2 in 1 type c...,692,440
4,portronics konnect l 1 2m fast charging 3a 8 p...,Product Name: portronics konnect l 1 2m fast c...,544,2393

In [15]:
df.to_csv(
    "C:\\Users\\kunja\\Downloads\\Ecommerce_Vector_RAG\\data\\processed\\amazon_products_features.csv",
    index=False
)